# Generated by Django 3.1.7 on 2022-01-05 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0002_auto_20220105_0842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obsmonitoring',
            old_name='nom',
            new_name='libelle',
        ),
    ]
