# Generated by Django 3.1.7 on 2022-01-06 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0004_pepiniere_semence_pepiniere'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('localite', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255, verbose_name='CONTACT FOURNISSEUR')),
            ],
            options={
                'verbose_name': 'fournisseur especes plants',
                'verbose_name_plural': 'FOURNISSEUS DES ESPECES',
            },
        ),
        migrations.RemoveField(
            model_name='pepiniere',
            name='contacts_fournisseur',
        ),
        migrations.RemoveField(
            model_name='pepiniere',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='semence_pepiniere',
            name='origine',
        ),
        migrations.AddField(
            model_name='semence_pepiniere',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametres.fournisseur'),
        ),
    ]
