# Generated by Django 3.1.7 on 2022-01-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0005_auto_20220106_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsSemenceEspece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='fournisseur',
            options={'verbose_name': 'fournisseur', 'verbose_name_plural': 'FOURNISSEURS'},
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='contact',
            field=models.CharField(max_length=255, verbose_name='CONTACT'),
        ),
        migrations.RemoveField(
            model_name='semence_pepiniere',
            name='details',
        ),
        migrations.AddField(
            model_name='semence_pepiniere',
            name='details',
            field=models.ManyToManyField(to='parametres.DetailsSemenceEspece'),
        ),
    ]
