# Generated by Django 3.1.7 on 2022-01-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0006_auto_20220106_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semence_pepiniere',
            name='details',
        ),
        migrations.AddField(
            model_name='semence_pepiniere',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
