# Generated by Django 3.1.7 on 2022-02-14 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0008_intitule_formation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prime',
            old_name='culture',
            new_name='libelle',
        ),
        migrations.RemoveField(
            model_name='prime',
            name='certification',
        ),
    ]
