# Generated by Django 3.1.7 on 2022-03-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0010_auto_20220216_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampagneProduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('annee', models.IntegerField(choices=[(2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, verbose_name='Année Campagne')),
            ],
        ),
    ]
