# Generated by Django 3.1.7 on 2022-02-08 12:47

import cooperatives.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametres', '0008_intitule_formation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailMonitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'details monitoring',
                'verbose_name_plural': 'DETAILS MONITORINGS ',
            },
        ),
        migrations.CreateModel(
            name='DetailPlanting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_plante', models.PositiveIntegerField(default=0, verbose_name='QTE recu')),
                ('espece', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parametres.espece')),
            ],
            options={
                'verbose_name': 'details planting',
                'verbose_name_plural': 'DETAILS PLANTINGS',
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formateur', models.CharField(max_length=255, verbose_name='FORMATEUR')),
                ('note_formateur', models.TextField(blank=True, null=True)),
                ('critere', models.CharField(blank=True, choices=[('SATISFAIT', 'SATISFAIT'), ('COMPRIS', 'COMPRIS'), ('NOSATISFAIT', 'PAS SATISFAIT'), ('PASCOMPRIS', 'PAS COMPRIS')], default='', max_length=50, null=True)),
                ('debut', models.DateField(verbose_name='DATE DEBUT')),
                ('fin', models.DateField(verbose_name='DATE FIN')),
                ('campagne', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parametres.campagne')),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.cooperative')),
                ('intitule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.intitule_formation')),
            ],
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='LE CODE PARCELLE EST GENERE AUTOMATIQUEMENT', max_length=150, null=True, verbose_name='CODE PARCELLE')),
                ('code_certificat', models.CharField(blank=True, max_length=150, null=True, verbose_name='CODE certification')),
                ('annee_certificat', models.IntegerField(blank=True, choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], null=True, verbose_name='Année certification')),
                ('annee_acquis', models.IntegerField(blank=True, choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], null=True, verbose_name='Année acquisition')),
                ('acquisition', models.CharField(choices=[('HERITAGE', 'HERITAGE'), ('ACHAT', 'ACHAT'), ('AUTRES', 'AUTRES')], default='heritage', max_length=50, verbose_name='MODE ACQUISITION')),
                ('latitude', models.CharField(blank=True, max_length=10, null=True)),
                ('longitude', models.CharField(blank=True, max_length=12, null=True)),
                ('superficie', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('culture', models.CharField(choices=[('ANACARDE', 'ANACARDE'), ('CACAO', 'CACAO'), ('CAFE', 'CAFE'), ('COTON', 'COTON'), ('HEVEA', 'HEVEA'), ('PALMIER', 'PALMIER A HUILE'), ('SOJA', 'SOJA'), ('AUTRE', 'AUTRE')], default='cacao', max_length=50, verbose_name='CULTURE')),
                ('certification', models.CharField(choices=[('UTZ', 'UTZ'), ('RA', 'RA'), ('BIO', 'BIO'), ('PROJET', 'PROJET'), ('AUTRE', 'AUTRE')], default='utz', max_length=50, verbose_name='CERTIFICATION')),
            ],
            options={
                'verbose_name': 'parcelle',
                'verbose_name_plural': 'PARCELLES',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Participantcoop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.cooperative')),
            ],
            options={
                'verbose_name': 'participant de la cooperative',
                'verbose_name_plural': 'PARTICIPANTS DE LA COOPERATIVE',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('responsable', models.CharField(blank=True, max_length=250, null=True)),
                ('contacts', models.CharField(blank=True, max_length=50, null=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='parametres.cooperative')),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'SECTIONS',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Sous_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('responsable', models.CharField(blank=True, max_length=250, null=True)),
                ('contacts', models.CharField(blank=True, max_length=50, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.section')),
            ],
            options={
                'verbose_name': 'sous section',
                'verbose_name_plural': 'SOUS SECTIONS',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Producteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150, unique=True, verbose_name='CODE PRODUCTEUR')),
                ('type_producteur', models.CharField(choices=[('MEMBRE', 'MEMBRE'), ('USAGER', 'USAGER')], default='MEMBRE', max_length=50, verbose_name='TYPE PRODUCTEUR')),
                ('genre', models.CharField(choices=[('H', 'HOMME'), ('F', 'FEMME')], default='H', max_length=2)),
                ('nom', models.CharField(max_length=250, verbose_name='Nom et prénoms')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date/Année de Naissance')),
                ('contacts', models.CharField(blank=True, max_length=50, null=True)),
                ('localite', models.CharField(blank=True, max_length=100, null=True)),
                ('nb_enfant', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('nb_epouse', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('enfant_scolarise', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Enfant Scolarise')),
                ('nb_personne', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Personne à Charge')),
                ('nb_parcelle', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to=cooperatives.models.producteurs_images, verbose_name='Logo')),
                ('type_document', models.CharField(choices=[('AUCUN', 'AUCUN'), ('ATTESTATION', 'ATTESTATION'), ('CNI', 'CNI'), ('PASSEPORT', 'PASSEPORT'), ('SEJOUR', 'CARTE DE SEJOUR'), ('CONSULAIRE', 'CARTE CONSULAIRE')], default='AUCUN', max_length=50, verbose_name='TYPE DOCUMENT')),
                ('num_document', models.CharField(blank=True, max_length=150, null=True, verbose_name='N° PIECE')),
                ('document', models.FileField(blank=True, null=True, upload_to=cooperatives.models.producteurs_documents, verbose_name='Documents')),
                ('is_active', models.BooleanField(default=False)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producteurs', to='parametres.cooperative')),
                ('origine', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='producteurs', to='parametres.origine')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producteurs', to='cooperatives.section')),
                ('sous_prefecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametres.sous_prefecture')),
                ('sous_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_section', to='cooperatives.sous_section')),
            ],
            options={
                'verbose_name': 'producteur',
                'verbose_name_plural': 'PRODUCTEURS',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_plant_exitant', models.PositiveIntegerField(default=0, verbose_name='NBRE PLANTS EXISTANTS')),
                ('plant_recus', models.PositiveIntegerField(default=0, verbose_name='NOMBRE DE PLANTS RECUS')),
                ('plant_total', models.PositiveIntegerField(default=0, verbose_name='NOMBRE TOTAL DE PLANTS')),
                ('date', models.DateField()),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantings', to='parametres.campagne')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantings', to='cooperatives.parcelle')),
                ('projet', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parametres.projet')),
            ],
            options={
                'verbose_name': 'planting',
                'verbose_name_plural': 'PLANTINGS',
                'ordering': ['parcelle'],
                'get_latest_by': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Participantformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.formation')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooperatives.participantcoop')),
            ],
            options={
                'verbose_name': 'participant de la formation',
                'verbose_name_plural': 'PARTICIPANTS DE LA FORMATION',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='parcelle',
            name='producteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to='cooperatives.producteur'),
        ),
        migrations.CreateModel(
            name='MonitoringEspece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mort', models.PositiveIntegerField(default=0, verbose_name='NBRE PLANTS MORTS')),
                ('taux_mortalite', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('detailmonitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.detailmonitoring')),
                ('detailplanting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.detailplanting')),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.espece')),
            ],
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mort_global', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='NBRE PLANTS MORTS')),
                ('mature_global', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='NBRE PLANTS VIVANTS')),
                ('date', models.DateField()),
                ('taux_vitalite', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('taux_mortalite', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observation', models.ManyToManyField(related_name='cooperatives_monitoring_observation', to='parametres.ObsMonitoring')),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.planting')),
            ],
            options={
                'verbose_name': 'monitoring planting',
                'verbose_name_plural': 'MONITORINGS PLANTINGS',
            },
        ),
        migrations.AddField(
            model_name='formation',
            name='participant',
            field=models.ManyToManyField(through='cooperatives.Participantformation', to='cooperatives.Participantcoop'),
        ),
        migrations.AddField(
            model_name='detailplanting',
            name='planting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.planting'),
        ),
        migrations.AddField(
            model_name='detailmonitoring',
            name='espece',
            field=models.ManyToManyField(through='cooperatives.MonitoringEspece', to='parametres.Espece'),
        ),
        migrations.AddField(
            model_name='detailmonitoring',
            name='monitoring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.monitoring'),
        ),
        migrations.CreateModel(
            name='Detail_Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.formation')),
                ('participant', models.ManyToManyField(to='cooperatives.Producteur')),
            ],
            options={
                'verbose_name': 'details formation',
                'verbose_name_plural': 'DETAILS FORMATIONS',
                'ordering': ['formation'],
            },
        ),
    ]
