# Generated by Django 3.1.7 on 2022-02-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelle',
            name='code_certificat',
            field=models.CharField(blank=True, max_length=150, null=True, unique=b'I01\n', verbose_name='CODE certification'),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='latitude',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='participantcoop',
            name='nom',
            field=models.CharField(max_length=255, unique=b'I01\n'),
        ),
    ]
