# Generated by Django 3.1.7 on 2022-02-09 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0008_intitule_formation'),
        ('cooperatives', '0004_auto_20220209_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringEspeceremplacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbrePlant', models.PositiveIntegerField(default=0, verbose_name='NOMBRE PLANTS REMPLACE')),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.espece')),
            ],
        ),
        migrations.CreateModel(
            name='RemplacementMonitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('espece', models.ManyToManyField(through='cooperatives.MonitoringEspeceremplacement', to='parametres.Espece')),
                ('monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.monitoring')),
            ],
        ),
        migrations.AddField(
            model_name='monitoringespeceremplacement',
            name='remplacement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.remplacementmonitoring'),
        ),
    ]
