# Generated by Django 3.1.7 on 2022-02-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0005_auto_20220209_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoringespeceremplacement',
            name='nbrePlant',
        ),
        migrations.AddField(
            model_name='monitoringespeceremplacement',
            name='recu',
            field=models.PositiveIntegerField(default=0, verbose_name='NOMBRE PLANTS RECU'),
        ),
        migrations.AddField(
            model_name='monitoringespeceremplacement',
            name='remplacer',
            field=models.PositiveBigIntegerField(default=0, verbose_name='NOMBRE PLANTS REMPLACER'),
        ),
    ]
