# Generated by Django 3.1.7 on 2022-02-10 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0008_intitule_formation'),
        ('cooperatives', '0006_auto_20220210_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringespeceremplacement',
            name='espece',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametres.espece'),
        ),
    ]
