# Generated by Django 3.1.7 on 2022-02-10 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0008_intitule_formation'),
        ('cooperatives', '0007_auto_20220210_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringespeceremplacement',
            name='espece',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parametres.espece'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monitoringespeceremplacement',
            name='recu',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='NOMBRE PLANTS RECU'),
        ),
        migrations.AlterField(
            model_name='monitoringespeceremplacement',
            name='remplacer',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='NOMBRE PLANTS REMPLACER'),
        ),
    ]
