# Generated by Django 3.1.7 on 2022-02-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0009_monitoringespeceremplacement_mort'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringespeceremplacement',
            name='futur',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='NOMBRE PLANTS PROCHAIN REMPLACEMENT'),
        ),
    ]
