# Generated by Django 3.1.7 on 2022-02-14 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0009_auto_20220214_1748'),
        ('cooperatives', '0010_monitoringespeceremplacement_futur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qteProduct', models.IntegerField(default=0)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.campagne')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.parcelle')),
            ],
            options={
                'verbose_name': 'production/parcelle',
                'verbose_name_plural': 'PRODUCTIONS/PARCELLES',
            },
        ),
    ]
