# Generated by Django 3.1.7 on 2022-02-15 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0011_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringespece',
            name='detailplanting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooperatives.detailplanting'),
        ),
    ]
