# Generated by Django 3.1.7 on 2022-02-15 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0013_auto_20220215_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailplantingremplacement',
            name='remplacer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooperatives.remplacementmonitoring'),
        ),
    ]
