# Generated by Django 3.1.7 on 2022-02-15 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0014_detailplantingremplacement_remplacer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailplantingremplacement',
            name='remplacer',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooperatives.remplacementmonitoring'),
        ),
    ]
