# Generated by Django 3.1.7 on 2022-02-16 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0009_auto_20220214_1748'),
        ('cooperatives', '0015_auto_20220215_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailplantingremplacement',
            name='remplacer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooperatives.remplacementmonitoring'),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='observation',
            field=models.ManyToManyField(blank=True, null=True, related_name='cooperatives_monitoring_observation', to='parametres.ObsMonitoring'),
        ),
    ]
