# Generated by Django 3.1.7 on 2022-03-16 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0011_campagneproduction'),
        ('cooperatives', '0016_auto_20220216_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='campagne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.campagneproduction'),
        ),
    ]
