# Generated by Django 3.1.7 on 2022-03-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0017_auto_20220316_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='annee',
            field=models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, verbose_name='Année Campagne'),
        ),
        migrations.AlterField(
            model_name='production',
            name='campagne',
            field=models.CharField(choices=[('petite', 'PETITE CAMPAGNE'), ('grande', 'GRANDE CAMPAGNE')], default='petite', max_length=150),
        ),
    ]
